ska-sa/katsdpingest

- katsdpingest/requirements-autotune.txt
requests and its dependencies were pinned to an older version.
katsdpdockerbaseline has a newer version.
Also updated 'docker' and dependencies, just to be on the safe side.
> Unpin some things in requirements-autotune.txt

- katsdpcam2telstate/scripts/cam2telstate.py
- katsdpingest/katsdpingest/ingest_session.py
- katsdpingest/katsdpingest/test/test_ingest_server.py
- katsdpingest/setup.py
See the blue text at
https://docs.google.com/document/d/1IwA3oWsin5AYjj9Ok8XiYHz21MximMaIxDC9MkfeYJ4/edit#heading=h.sk8r3fbnyn29
for a description of the interface.
It will still need some testing to verify that the CPU can do the
calculation of the per-visibility flags fast enough - if not, that'll
have to be moved to the GPU.
See SPR1-187.
> Support multiple channel masks selected by baseline length

- katsdpingest/katsdpingest/ingest_kernels/prepare_flags.mako
- katsdpingest/katsdpingest/ingest_session.py
- katsdpingest/katsdpingest/sigproc.py
- katsdpingest/katsdpingest/test/test_ingest_server.py
- katsdpingest/katsdpingest/test/test_ingest_session.py
- katsdpingest/katsdpingest/test/test_sigproc.py
Expanding channel_mask and channel_mask_idx into a per-visibility flag
was too slow on the CPU. It's now mostly done on the CPU, although the
channel_mask and channel_data_suspect sensors are now combined into one
array on the CPU to pass to the GPU. This has been performance-tested
with a 32K simulation on site.
> Move flag preparation to the GPU

- katsdpingest/requirements.txt
The new flagging code uses some features from katpoint master that
aren't available in a PyPI release yet.
> Install katpoint from master

- katsdpingest/ingest_session.py
spead2 (up to 1.14) creates some cyclic garbage, and it seems that
sometimes it just doesn't get collected over multiple
capture-init/capture-done cycles.
> Run explicit garbage collection after capture-done

- katsdpingest/utils.py
This is needed to get input_labels, which are a proxy-level sensor
rather than instrument-level.
> Search 'cbf' namespace after instrument namespace

- katsdpingest/sigproc.py
For some choices of tuning parameters the dimensions need to be padded
to a multiple of 3, but that wasn't done with the test problem used for
autotuning. As a result those configurations were skipping during
tuning.
In testing on my laptop, the Prepare kernel now finds one of these
skipped configurations to be best.
See SPR1-230.
> Fix sizing of sample problem in autotuning

- katsdpingest/ingest_session.py
- katsdpingest/sigproc.py
- katsdpingest/test/test_ingest_server.py
- katsdpingest/test/test_sigproc.py
This replaces the hard-coded copy of the flag definitions.
See SPR1-185.
> Use katdal.flags module

- katsdpingest/ingest_kernels/postproc.mako
- katsdpingest/test/test_sigproc.py
These occur during excision if the un-excised visibilities sum to zero
but the excised visibilities (which are down-weighted by 2**-64) leave a
residual that's extremely small.
This should help with SR-1946.
> Correct visibilities that are small but should be zero

- katsdpingest/ingest_kernels/prepare_flags.mako
- katsdpingest/sigproc.py
- katsdpingest/test/test_sigproc.py
CBF fills in zeros for lost or otherwise unusable data, and the
sensor-provided CAM flags are insufficient to flag all such cases.
> Apply the CAM flag to visibilities that are zero

- mypy.ini
Now that katsdpsigproc is Python 3.6 only.
> Bump to Python 3.6 in mypy.ini

- katsdpingest/receiver.py
CBF have spaced out the packet delivery so that it fills the
accumulation time, and jitter can then cause a little overlap at the
boundary between dumps that was leading to heaps being prematurely
ejected. Throw more memory at the problem.
Closes SPR1-501.
> Allow for overlapping dumps

- katsdpingest/ingest_session.py
Mypy can't figure out that capture_block_id is not None during _run, so
we have to assert it.
> Fix a mypy error once katsdptelstate has type annotations

- Jenkinsfile
- katsdpingest/ingest_session.py
- katsdpingest/test/test_ingest_server.py
- requirements.txt
- setup.py
To avoid things getting overly complicated, I've removed support for baseline-dependent RFI masks from CAM. @ajoubertza has confirmed that CAM haven't implemented it, and trying to merge them with the RFI mask model would have made the already somewhat complicated code slightly hairy.
The unit tests have slightly more rework than might be expected, because I discovered that some of the testing was done by fiddling with data outside of the channel range being processed by the system-under-test and hence was useless.
This should continue to work without an RFI mask available, but it will print a warning about the CAM-supplied mask being 2D because cam2telstate currently converts the CAM sensor into a 2D array in anticipation of baseline-dependent masks. Once this is deployed merged I can …
> Use RFI mask from model

- katsdpingest/ingest_server.py
- katsdpingest/ingest_session.py
It counts time fetching sensors during the capture process, so that if
we start dropping data again we can tell whether it was caused by a slow
telstate.
> Add sensor for time spent in telstate

- katsdpingest/ingest_session.py
math.gcd was introducted in Python 3.5 and fractions.gcd is being
removed in 3.9.
> Switch fractions.gcd -> math.gcd

- katsdpingest/ingest_server.py
- katsdpingest/ingest_session.py
- katsdpingest/receiver.py
- katsdpingest/sigproc.py
- katsdpingest/test/test_ingest_server.py
- katsdpingest/test/test_ingest_session.py
- katsdpingest/utils.py
- requirements.txt
- scripts/ingest.py
- setup.py
This doesn't have any significant immediate benefits, but it sets the scene for making things more robust when telstate has high latency e.g. by not waiting.
The code had to change quite substantially because constructors can't be asynchronous, and the CBFIngest constructor had a lot of interaction with telstate. This is resolved by
- adding a SystemAttrs class which holds the static configuration that is queried from telstate on startup (and which has an asynchronous factory function to build it); and
- keeping a log of items to add to telstate, and using a separate `populate_telstate` method to actually add them after construction.
I went through a number of iterations on this and there may be some left-over warts - if something looks odd or appears to have changed for no good reason, …
> Use asyncio telstate

- katsdpingest/ingest_session.py
- katsdpingest/test/test_ingest_session.py
- scripts/ingest.py
Instead of querying the latest values from telstate as they are needed, utilise watch_key to do pub-sub and track the latest value (for sdisp sensors) or maintain a sliding window of values (for CBF-related sensors, to match the sensor timestamps to the data timestamps). This should prevent blocking ingest when telstate is slow; instead, stale values might be used until telstate catches up.
> No telstate delays

- katsdpingest/ingest_server.py
- katsdpingest/ingest_session.py
It was no longer connected to anything, as ingest no longer blocks
waiting to query telstate.
> Remove the telstate-seconds-total sensor

- katsdpingest/ingest_session.py
- katsdpingest/receiver.py
- katsdpingest/test/test_ingest_session.py
The main bug was that sensor timestamps were incorrectly converted to
dump indices, because self.rx.timestamp_base was read before it was
initialised (and hence was 0). To avoid such silent bugs in future,
timebase_base now starts life as None rather than 0.
There is a deeper design flaw, in that sensor values may be received
before the first piece of data, at which point it's impossible to
convert timestamps to dump indices. This is fixed by changing the
SensorHistory class to work with timestamps instead of dump indices.
This removes the optimisation that allowed multiple updates of a sensor
during a single dump to be collapsed.
There was a secondary bug that if a sensor sample was received "late"
(i.e. after the value was already queried for the subsequent dump), it
was dropped …
> Fix some issues in SensorHistory

- katsdpingest/ingest_session.py
I am also wondering if we should downgrade the sensor update INFO logging (specifically the two log lines in _update_sensor). This is being triggered quite regularly by the data_suspect sensors now and is a little polluting....
> Minor logging fix

- katsdpingest/ingest_session.py
- katsdpingest/test/test_ingest_server.py
In some cases this can result in an extra channel being masked, if less
than half of it overlaps the masked region.
> Pass channel width when sampling RFI and band-mask models

- katsdpingest/test/test_ingest_server.py
This is a regression test for the bug fixed in
ska-sa/katsdptelstate#116.
> Test with small number of threads in ThreadPoolExecutor

- katsdpingest/ingest_session.py
It doesn't seem to realise that one doesn't need to explicitly import
np.lib.stride_tricks.
> One-liner to keep mypy happy with np.lib.stride_tricks

- katsdpingest/sigproc.py
The C code contains `for` loops to ensure that a single workgroup along
the baseline (fastest-varying) dimension processes the full extent of
the dimension. But the calculation of the global size didn't take this
into account, so it created multiple workgroups along this dimension.
They ended up repeating the same work, possibly hundreds of times,
making compress_weights by far the dominant use of the GPU.
I bumped the autotuning version to force tuning to be re-run, since the
previous tuning results may have been thrown off.
> Fix repeated computation by CompressWeights kernel

- katsdpingest/ingest_session.py
- katsdpingest/test/test_ingest_session.py
Collapsing the RFI masks to unique channel masks used np.unique, which
possibly due to https://github.com/numpy/numpy/issues/11136 is very slow
(around 15s in the worst case for MeerKAT). The scikit-image version
from that ticket is about 500x faster.
Closes SPR1-1046.
> Speed up startup

- scripts/ingest.py
This removes the direct dependency on aioredis, and so paves the way to
upgrading to 2.x.
Depends on https://github.com/ska-sa/katsdptelstate/pull/125.
> Use katsdptelstate.aio.redis.RedisBackend.from_url

- Dockerfile
Explicitly grant `cap_net_raw+p` capabilities to capambel so that it may pass them on.
> Add `cap_net_raw` capabilities

- .pre-commit-config.yaml
- Jenkinsfile
- jenkins-autotune.sh
For now the image is pushed to both Harbor (a.k.a. DOCKER_REGISTRY2) while still falling back to pushing to DOCKER_REGISTRY.
I also added a `trap` command to ensure the images are deleted after pushing, to avoid filling up the disk so quickly.
Relates to SPR1-200.
> Push tuned images to Harbor
